### ISSUE TITLE
Followed TODO implementation and failed on first run

### ISSUE THREAD

**Issue by bownah** [ActionsDesk/github-org-member-email-action#3]
### Describe the bug

In Get Member Emails step:

Run ActionsDesk/github-org-member-email-action@v1.0.0
/home/runner/work/_actions/ActionsDesk/github-org-member-email-action/v1.0.0/dist/index.js:7
 */function isObject(e){return Object.prototype.toString.call(e)==="[object Object]"}function isPlainObject(e){var p,a;if(isObject(e)===false)return false;p=e.constructor;if(p===undefined)return true;a=p.prototype;if(isObject(a)===false)return false;if(a.hasOwnProperty("isPrototypeOf")===false){return false}return true}p.isPlainObject=isPlainObject},8948:(e,p,a)=>{"use strict";Object.defineProperty(p,"__esModule",{value:true});function _interopDefault(e){return e&&typeof e==="object"&&"default"in e?e["default"]:e}var d=_interopDefault(a(2413));var t=_interopDefault(a(8[6](https://github.com/bownah/ahd-users/runs/5272979963?check_suite_focus=true#step:3:6)05));var r=_interopDefault(a(8835));var i=_interopDefault(a([7](https://github.com/bownah/ahd-users/runs/5272979963?check_suite_focus=true#step:3:7)712));var s=_interopDefault(a(7211));var o=_interopDefault(a([8](https://github.com/bownah/ahd-users/runs/5272979963?check_suite_focus=true#step:3:8)761));const n=d.Readable;const l=Symbol("buffer");const m=Symbol("type");class Blob{constructor(){this[m]="";const e=arguments[0];const p=arguments[1];const a=[];let d=0;if(e){const p=e;const t=Number(p.length);for(let e=0;e<t;e++

TypeError: Cannot read property 'login' of undefined
    at /home/runner/work/_actions/ActionsDesk/github-org-member-email-action/v1.0.0/dist/index.js:7:322787
    at /home/runner/work/_actions/ActionsDesk/github-org-member-email-action/v1.0.0/dist/index.js:7:327036
    at Object.<anonymous> (/home/runner/work/_actions/ActionsDesk/github-org-member-email-action/v1.0.0/dist/index.js:7:327075)
    at Module._compile (internal/modules/cjs/loader.js:[9](https://github.com/bownah/ahd-users/runs/5272979963?check_suite_focus=true#step:3:9)59:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:[10](https://github.com/bownah/ahd-users/runs/5272979963?check_suite_focus=true#step:3:10))
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:[11](https://github.com/bownah/ahd-users/runs/5272979963?check_suite_focus=true#step:3:11)

### To Reproduce

1. Create action as per example on README page (complete copy/paste)
2. Created ORG_TOKEN secret as specified
3. Manual run of action

**Comment by nicklegan** [comment]
👋 This Action works fine, make sure you set [the correct scope](https://github.com/ActionsDesk/github-org-member-email-action#github-secrets) on the token.
